package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class Applied extends GraphExpr {
  public final String uident_;
  public final Actuals actuals_;

  public Applied(String p1, Actuals p2) { uident_ = p1; actuals_ = p2; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.GraphExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.Applied) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.Applied x = (com.biosimilarity.GraphL.model.GraphL.Absyn.Applied)o;
      return this.uident_.equals(x.uident_) && this.actuals_.equals(x.actuals_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.uident_.hashCode())+this.actuals_.hashCode();
  }


}
