package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public abstract class ConditionOrDecl implements java.io.Serializable {
  public abstract <R,A> R accept(ConditionOrDecl.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.ConditionIn p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.DeclIn p, A arg);

  }

}
