package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public abstract class Condition implements java.io.Serializable {
  public abstract <R,A> R accept(Condition.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.ConjunctionCondition p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.DisjunctionCondition p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.StructuralCondition p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.BaseCondition p, A arg);

  }

}
