package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class EdgeVariable extends EdgeLabel {
  public final String lident_;

  public EdgeVariable(String p1) { lident_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeLabel.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeVariable) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeVariable x = (com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeVariable)o;
      return this.lident_.equals(x.lident_);
    }
    return false;
  }

  public int hashCode() {
    return this.lident_.hashCode();
  }


}
