package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class EdgePatternStruct extends EdgeExprPattern {
  public final EdgeDeconstructor edgedeconstructor_;

  public EdgePatternStruct(EdgeDeconstructor p1) { edgedeconstructor_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeExprPattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.EdgePatternStruct) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.EdgePatternStruct x = (com.biosimilarity.GraphL.model.GraphL.Absyn.EdgePatternStruct)o;
      return this.edgedeconstructor_.equals(x.edgedeconstructor_);
    }
    return false;
  }

  public int hashCode() {
    return this.edgedeconstructor_.hashCode();
  }


}
