package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class EdgeExtensionForm extends EdgeExtension {
  public final ListEdge listedge_;

  public EdgeExtensionForm(ListEdge p1) { listedge_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeExtension.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeExtensionForm) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeExtensionForm x = (com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeExtensionForm)o;
      return this.listedge_.equals(x.listedge_);
    }
    return false;
  }

  public int hashCode() {
    return this.listedge_.hashCode();
  }


}
