package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public abstract class GraphExpr implements java.io.Serializable {
  public abstract <R,A> R accept(GraphExpr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.Isolated p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.Selected p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.Connected p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.Recursed p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.Pointed p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.Variable p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.Applied p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.Empty p, A arg);

  }

}
