package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class GraphExtensionBuiltinExpr extends GraphExtension {
  public final GraphExtensionBuiltin graphextensionbuiltin_;

  public GraphExtensionBuiltinExpr(GraphExtensionBuiltin p1) { graphextensionbuiltin_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.GraphExtension.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.GraphExtensionBuiltinExpr) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.GraphExtensionBuiltinExpr x = (com.biosimilarity.GraphL.model.GraphL.Absyn.GraphExtensionBuiltinExpr)o;
      return this.graphextensionbuiltin_.equals(x.graphextensionbuiltin_);
    }
    return false;
  }

  public int hashCode() {
    return this.graphextensionbuiltin_.hashCode();
  }


}
