package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class GraphIntension extends GraphCollection {
  public final GraphComprehension graphcomprehension_;

  public GraphIntension(GraphComprehension p1) { graphcomprehension_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.GraphCollection.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.GraphIntension) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.GraphIntension x = (com.biosimilarity.GraphL.model.GraphL.Absyn.GraphIntension)o;
      return this.graphcomprehension_.equals(x.graphcomprehension_);
    }
    return false;
  }

  public int hashCode() {
    return this.graphcomprehension_.hashCode();
  }


}
