package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class Isolated extends GraphExpr {
  public final GraphExpr graphexpr_1, graphexpr_2;

  public Isolated(GraphExpr p1, GraphExpr p2) { graphexpr_1 = p1; graphexpr_2 = p2; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.GraphExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.Isolated) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.Isolated x = (com.biosimilarity.GraphL.model.GraphL.Absyn.Isolated)o;
      return this.graphexpr_1.equals(x.graphexpr_1) && this.graphexpr_2.equals(x.graphexpr_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.graphexpr_1.hashCode())+this.graphexpr_2.hashCode();
  }


}
