package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class LRBoundGraph extends GraphBinding {
  public final GraphDeconstructor graphdeconstructor_;
  public final GraphExpr graphexpr_;

  public LRBoundGraph(GraphDeconstructor p1, GraphExpr p2) { graphdeconstructor_ = p1; graphexpr_ = p2; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.GraphBinding.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.LRBoundGraph) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.LRBoundGraph x = (com.biosimilarity.GraphL.model.GraphL.Absyn.LRBoundGraph)o;
      return this.graphdeconstructor_.equals(x.graphdeconstructor_) && this.graphexpr_.equals(x.graphexpr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.graphdeconstructor_.hashCode())+this.graphexpr_.hashCode();
  }


}
