package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class LRBoundEdge extends EdgeBinding {
  public final EdgeDeconstructor edgedeconstructor_;
  public final EdgeExpr edgeexpr_;

  public LRBoundEdge(EdgeDeconstructor p1, EdgeExpr p2) { edgedeconstructor_ = p1; edgeexpr_ = p2; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeBinding.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.LRBoundEdge) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.LRBoundEdge x = (com.biosimilarity.GraphL.model.GraphL.Absyn.LRBoundEdge)o;
      return this.edgedeconstructor_.equals(x.edgedeconstructor_) && this.edgeexpr_.equals(x.edgeexpr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.edgedeconstructor_.hashCode())+this.edgeexpr_.hashCode();
  }


}
