package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class LRGenEdge extends EdgeGenerator {
  public final EdgeDeconstructor edgedeconstructor_;
  public final EdgeCollection edgecollection_;

  public LRGenEdge(EdgeDeconstructor p1, EdgeCollection p2) { edgedeconstructor_ = p1; edgecollection_ = p2; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeGenerator.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.LRGenEdge) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.LRGenEdge x = (com.biosimilarity.GraphL.model.GraphL.Absyn.LRGenEdge)o;
      return this.edgedeconstructor_.equals(x.edgedeconstructor_) && this.edgecollection_.equals(x.edgecollection_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.edgedeconstructor_.hashCode())+this.edgecollection_.hashCode();
  }


}
