package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class Nullity extends AtomicFormula {

  public Nullity() { }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.AtomicFormula.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.Nullity) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
