package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class Selected extends GraphExpr {
  public final SelectionExpr selectionexpr_;

  public Selected(SelectionExpr p1) { selectionexpr_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.GraphExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.Selected) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.Selected x = (com.biosimilarity.GraphL.model.GraphL.Absyn.Selected)o;
      return this.selectionexpr_.equals(x.selectionexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.selectionexpr_.hashCode();
  }


}
