package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public abstract class StructureCondition implements java.io.Serializable {
  public abstract <R,A> R accept(StructureCondition.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.GraphIsolatedCond p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.GraphPointedCond p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.GraphConnectedCond p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.GraphStructureLiteral p, A arg);

  }

}
