package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public abstract class VertexSelectionExpr implements java.io.Serializable {
  public abstract <R,A> R accept(VertexSelectionExpr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexSelection p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexIntensionSelection p, A arg);

  }

}
