package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public abstract class VertexExpr implements java.io.Serializable {
  public abstract <R,A> R accept(VertexExpr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexSum p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexMult p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexLiteral p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexVariable p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexNegated p, A arg);

  }

}
