package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public abstract class VertexCollection implements java.io.Serializable {
  public abstract <R,A> R accept(VertexCollection.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexIntension p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexExtenionExpr p, A arg);

  }

}
