package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public abstract class VertexStructureCondition implements java.io.Serializable {
  public abstract <R,A> R accept(VertexStructureCondition.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexStructureSum p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexStructureMult p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexStructureLiteral p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexStructureVariable p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexStructureNegated p, A arg);

  }

}
