package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class VertexComprehensionForm extends VertexComprehension {
  public final VertexGenerator vertexgenerator_;
  public final ListConditionOrDecl listconditionordecl_;

  public VertexComprehensionForm(VertexGenerator p1, ListConditionOrDecl p2) { vertexgenerator_ = p1; listconditionordecl_ = p2; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexComprehension.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.VertexComprehensionForm) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.VertexComprehensionForm x = (com.biosimilarity.GraphL.model.GraphL.Absyn.VertexComprehensionForm)o;
      return this.vertexgenerator_.equals(x.vertexgenerator_) && this.listconditionordecl_.equals(x.listconditionordecl_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.vertexgenerator_.hashCode())+this.listconditionordecl_.hashCode();
  }


}
