package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class VertexExtensionForm extends VertexExtension {
  public final ListVertex listvertex_;

  public VertexExtensionForm(ListVertex p1) { listvertex_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexExtension.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.VertexExtensionForm) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.VertexExtensionForm x = (com.biosimilarity.GraphL.model.GraphL.Absyn.VertexExtensionForm)o;
      return this.listvertex_.equals(x.listvertex_);
    }
    return false;
  }

  public int hashCode() {
    return this.listvertex_.hashCode();
  }


}
