package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class VertexIntension extends VertexCollection {
  public final VertexComprehension vertexcomprehension_;

  public VertexIntension(VertexComprehension p1) { vertexcomprehension_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexCollection.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.VertexIntension) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.VertexIntension x = (com.biosimilarity.GraphL.model.GraphL.Absyn.VertexIntension)o;
      return this.vertexcomprehension_.equals(x.vertexcomprehension_);
    }
    return false;
  }

  public int hashCode() {
    return this.vertexcomprehension_.hashCode();
  }


}
