package com.biosimilarity.GraphL.model.GraphL;

import com.biosimilarity.GraphL.model.GraphL.Absyn.*;

/** BNFC-Generated All Visitor */
public interface AllVisitor<R,A> extends
  com.biosimilarity.GraphL.model.GraphL.Absyn.GraphExpr.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.Formals.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.Actuals.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.SelectionExpr.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.VertexSelectionExpr.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.Comprehension.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.VertexComprehension.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeComprehension.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.GraphComprehension.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.VertexBinding.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeBinding.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.GraphBinding.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.Binding.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.VertexGenerator.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeGenerator.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.GraphGenerator.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.Generator.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.VertexExpr.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.VertexDeconstructor.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.VertexActual.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeExpr.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.EdgePlus.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeLabel.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeExprPattern.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeActual.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeDeconstructor.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.GraphDeconstructor.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.LogicalOrDecl.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.Satisfaction.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.Decl.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.VertexCollection.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeCollection.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.GraphCollection.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.VertexExtension.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeExtension.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.GraphExtension.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.VertexExtensionBuiltin.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeExtensionBuiltin.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.GraphExtensionBuiltin.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.Condition.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.StructureCondition.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.VertexStructureCondition.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeLabelCondition.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.GroundCondition.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.VertexBuiltin.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.GraphBuiltin.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.AtomicFormula.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.Edge.Visitor<R,A>,
  com.biosimilarity.GraphL.model.GraphL.Absyn.Vertex.Visitor<R,A>
{}
