package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public abstract class Actuals implements java.io.Serializable {
  public abstract <R,A> R accept(Actuals.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.ActualsFullForm p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.ActualsVertexForm p, A arg);

  }

}
