package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class BoundGraph extends Binding {
  public final GraphBinding graphbinding_;

  public BoundGraph(GraphBinding p1) { graphbinding_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.Binding.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.BoundGraph) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.BoundGraph x = (com.biosimilarity.GraphL.model.GraphL.Absyn.BoundGraph)o;
      return this.graphbinding_.equals(x.graphbinding_);
    }
    return false;
  }

  public int hashCode() {
    return this.graphbinding_.hashCode();
  }


}
