package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class ComprehensionForm extends Comprehension {
  public final Generator generator_;
  public final ListLogicalOrDecl listlogicalordecl_;

  public ComprehensionForm(Generator p1, ListLogicalOrDecl p2) { generator_ = p1; listlogicalordecl_ = p2; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.Comprehension.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.ComprehensionForm) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.ComprehensionForm x = (com.biosimilarity.GraphL.model.GraphL.Absyn.ComprehensionForm)o;
      return this.generator_.equals(x.generator_) && this.listlogicalordecl_.equals(x.listlogicalordecl_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.generator_.hashCode())+this.listlogicalordecl_.hashCode();
  }


}
