package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class ConjunctionCondition extends Condition {
  public final Condition condition_1, condition_2;

  public ConjunctionCondition(Condition p1, Condition p2) { condition_1 = p1; condition_2 = p2; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.Condition.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.ConjunctionCondition) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.ConjunctionCondition x = (com.biosimilarity.GraphL.model.GraphL.Absyn.ConjunctionCondition)o;
      return this.condition_1.equals(x.condition_1) && this.condition_2.equals(x.condition_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.condition_1.hashCode())+this.condition_2.hashCode();
  }


}
