package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class DeclIn extends LogicalOrDecl {
  public final Decl decl_;

  public DeclIn(Decl p1) { decl_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.LogicalOrDecl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.DeclIn) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.DeclIn x = (com.biosimilarity.GraphL.model.GraphL.Absyn.DeclIn)o;
      return this.decl_.equals(x.decl_);
    }
    return false;
  }

  public int hashCode() {
    return this.decl_.hashCode();
  }


}
