package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class EdgePatternDecon extends EdgeDeconstructor {
  public final EdgeLabel edgelabel_;
  public final VertexDeconstructor vertexdeconstructor_1, vertexdeconstructor_2;

  public EdgePatternDecon(EdgeLabel p1, VertexDeconstructor p2, VertexDeconstructor p3) { edgelabel_ = p1; vertexdeconstructor_1 = p2; vertexdeconstructor_2 = p3; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeDeconstructor.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.EdgePatternDecon) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.EdgePatternDecon x = (com.biosimilarity.GraphL.model.GraphL.Absyn.EdgePatternDecon)o;
      return this.edgelabel_.equals(x.edgelabel_) && this.vertexdeconstructor_1.equals(x.vertexdeconstructor_1) && this.vertexdeconstructor_2.equals(x.vertexdeconstructor_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.edgelabel_.hashCode())+this.vertexdeconstructor_1.hashCode())+this.vertexdeconstructor_2.hashCode();
  }


}
