package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class EdgeJudgement extends Satisfaction {
  public final EdgeDeconstructor edgedeconstructor_;
  public final EdgeLabelCondition edgelabelcondition_;

  public EdgeJudgement(EdgeDeconstructor p1, EdgeLabelCondition p2) { edgedeconstructor_ = p1; edgelabelcondition_ = p2; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.Satisfaction.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeJudgement) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeJudgement x = (com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeJudgement)o;
      return this.edgedeconstructor_.equals(x.edgedeconstructor_) && this.edgelabelcondition_.equals(x.edgelabelcondition_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.edgedeconstructor_.hashCode())+this.edgelabelcondition_.hashCode();
  }


}
