package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class FormalsVertexForm extends Formals {
  public final ListLIdent listlident_;

  public FormalsVertexForm(ListLIdent p1) { listlident_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.Formals.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.FormalsVertexForm) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.FormalsVertexForm x = (com.biosimilarity.GraphL.model.GraphL.Absyn.FormalsVertexForm)o;
      return this.listlident_.equals(x.listlident_);
    }
    return false;
  }

  public int hashCode() {
    return this.listlident_.hashCode();
  }


}
