package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class FormalsFullForm extends Formals {
  public final ListLIdent listlident_1, listlident_2;

  public FormalsFullForm(ListLIdent p1, ListLIdent p2) { listlident_1 = p1; listlident_2 = p2; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.Formals.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.FormalsFullForm) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.FormalsFullForm x = (com.biosimilarity.GraphL.model.GraphL.Absyn.FormalsFullForm)o;
      return this.listlident_1.equals(x.listlident_1) && this.listlident_2.equals(x.listlident_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listlident_1.hashCode())+this.listlident_2.hashCode();
  }


}
