package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class GraphJudgement extends Satisfaction {
  public final GraphDeconstructor graphdeconstructor_;
  public final Condition condition_;

  public GraphJudgement(GraphDeconstructor p1, Condition p2) { graphdeconstructor_ = p1; condition_ = p2; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.Satisfaction.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.GraphJudgement) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.GraphJudgement x = (com.biosimilarity.GraphL.model.GraphL.Absyn.GraphJudgement)o;
      return this.graphdeconstructor_.equals(x.graphdeconstructor_) && this.condition_.equals(x.condition_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.graphdeconstructor_.hashCode())+this.condition_.hashCode();
  }


}
