package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class GraphPointedCond extends StructureCondition {
  public final VertexStructureCondition vertexstructurecondition_;

  public GraphPointedCond(VertexStructureCondition p1) { vertexstructurecondition_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.StructureCondition.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.GraphPointedCond) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.GraphPointedCond x = (com.biosimilarity.GraphL.model.GraphL.Absyn.GraphPointedCond)o;
      return this.vertexstructurecondition_.equals(x.vertexstructurecondition_);
    }
    return false;
  }

  public int hashCode() {
    return this.vertexstructurecondition_.hashCode();
  }


}
