package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class JudgmentExpr extends LogicalOrDecl {
  public final Satisfaction satisfaction_;

  public JudgmentExpr(Satisfaction p1) { satisfaction_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.LogicalOrDecl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.JudgmentExpr) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.JudgmentExpr x = (com.biosimilarity.GraphL.model.GraphL.Absyn.JudgmentExpr)o;
      return this.satisfaction_.equals(x.satisfaction_);
    }
    return false;
  }

  public int hashCode() {
    return this.satisfaction_.hashCode();
  }


}
