package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class LRGenVertex extends VertexGenerator {
  public final VertexDeconstructor vertexdeconstructor_;
  public final VertexCollection vertexcollection_;

  public LRGenVertex(VertexDeconstructor p1, VertexCollection p2) { vertexdeconstructor_ = p1; vertexcollection_ = p2; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexGenerator.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.LRGenVertex) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.LRGenVertex x = (com.biosimilarity.GraphL.model.GraphL.Absyn.LRGenVertex)o;
      return this.vertexdeconstructor_.equals(x.vertexdeconstructor_) && this.vertexcollection_.equals(x.vertexcollection_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.vertexdeconstructor_.hashCode())+this.vertexcollection_.hashCode();
  }


}
