package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public abstract class Satisfaction implements java.io.Serializable {
  public abstract <R,A> R accept(Satisfaction.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexJudgement p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeJudgement p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.GraphJudgement p, A arg);

  }

}
