package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class SourceBuiltin extends VertexBuiltin {
  public final VertexExpr vertexexpr_;

  public SourceBuiltin(VertexExpr p1) { vertexexpr_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexBuiltin.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.SourceBuiltin) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.SourceBuiltin x = (com.biosimilarity.GraphL.model.GraphL.Absyn.SourceBuiltin)o;
      return this.vertexexpr_.equals(x.vertexexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.vertexexpr_.hashCode();
  }


}
