package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class VertexJudgement extends Satisfaction {
  public final VertexDeconstructor vertexdeconstructor_;
  public final VertexStructureCondition vertexstructurecondition_;

  public VertexJudgement(VertexDeconstructor p1, VertexStructureCondition p2) { vertexdeconstructor_ = p1; vertexstructurecondition_ = p2; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.Satisfaction.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.VertexJudgement) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.VertexJudgement x = (com.biosimilarity.GraphL.model.GraphL.Absyn.VertexJudgement)o;
      return this.vertexdeconstructor_.equals(x.vertexdeconstructor_) && this.vertexstructurecondition_.equals(x.vertexstructurecondition_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.vertexdeconstructor_.hashCode())+this.vertexstructurecondition_.hashCode();
  }


}
