package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class VertexExtensionBuiltinExpr extends VertexExtension {
  public final VertexExtensionBuiltin vertexextensionbuiltin_;

  public VertexExtensionBuiltinExpr(VertexExtensionBuiltin p1) { vertexextensionbuiltin_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexExtension.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.VertexExtensionBuiltinExpr) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.VertexExtensionBuiltinExpr x = (com.biosimilarity.GraphL.model.GraphL.Absyn.VertexExtensionBuiltinExpr)o;
      return this.vertexextensionbuiltin_.equals(x.vertexextensionbuiltin_);
    }
    return false;
  }

  public int hashCode() {
    return this.vertexextensionbuiltin_.hashCode();
  }


}
