package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class ActualsVertexForm extends Actuals {
  public final ListVertexActual listvertexactual_;

  public ActualsVertexForm(ListVertexActual p1) { listvertexactual_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.Actuals.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.ActualsVertexForm) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.ActualsVertexForm x = (com.biosimilarity.GraphL.model.GraphL.Absyn.ActualsVertexForm)o;
      return this.listvertexactual_.equals(x.listvertexactual_);
    }
    return false;
  }

  public int hashCode() {
    return this.listvertexactual_.hashCode();
  }


}
