package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public abstract class AtomicFormula implements java.io.Serializable {
  public abstract <R,A> R accept(AtomicFormula.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.Verity p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.Absurdity p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.Nullity p, A arg);

  }

}
