package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class BoundVertex extends Binding {
  public final VertexBinding vertexbinding_;

  public BoundVertex(VertexBinding p1) { vertexbinding_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.Binding.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.BoundVertex) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.BoundVertex x = (com.biosimilarity.GraphL.model.GraphL.Absyn.BoundVertex)o;
      return this.vertexbinding_.equals(x.vertexbinding_);
    }
    return false;
  }

  public int hashCode() {
    return this.vertexbinding_.hashCode();
  }


}
