package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class Connected extends GraphExpr {
  public final EdgePlus edgeplus_;
  public final VertexSelectionExpr vertexselectionexpr_1, vertexselectionexpr_2;

  public Connected(EdgePlus p1, VertexSelectionExpr p2, VertexSelectionExpr p3) { edgeplus_ = p1; vertexselectionexpr_1 = p2; vertexselectionexpr_2 = p3; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.GraphExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.Connected) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.Connected x = (com.biosimilarity.GraphL.model.GraphL.Absyn.Connected)o;
      return this.edgeplus_.equals(x.edgeplus_) && this.vertexselectionexpr_1.equals(x.vertexselectionexpr_1) && this.vertexselectionexpr_2.equals(x.vertexselectionexpr_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.edgeplus_.hashCode())+this.vertexselectionexpr_1.hashCode())+this.vertexselectionexpr_2.hashCode();
  }


}
