package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class EdgeActualized extends EdgeActual {
  public final EdgeLabel edgelabel_;

  public EdgeActualized(EdgeLabel p1) { edgelabel_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeActual.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeActualized) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeActualized x = (com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeActualized)o;
      return this.edgelabel_.equals(x.edgelabel_);
    }
    return false;
  }

  public int hashCode() {
    return this.edgelabel_.hashCode();
  }


}
