package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class EdgeExtensionBuiltinExpr extends EdgeExtension {
  public final EdgeExtensionBuiltin edgeextensionbuiltin_;

  public EdgeExtensionBuiltinExpr(EdgeExtensionBuiltin p1) { edgeextensionbuiltin_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeExtension.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeExtensionBuiltinExpr) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeExtensionBuiltinExpr x = (com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeExtensionBuiltinExpr)o;
      return this.edgeextensionbuiltin_.equals(x.edgeextensionbuiltin_);
    }
    return false;
  }

  public int hashCode() {
    return this.edgeextensionbuiltin_.hashCode();
  }


}
