package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public abstract class EdgeBinding implements java.io.Serializable {
  public abstract <R,A> R accept(EdgeBinding.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.LRBoundEdge p, A arg);

  }

}
