package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public abstract class EdgeExprPattern implements java.io.Serializable {
  public abstract <R,A> R accept(EdgeExprPattern.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeExprLabel p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.EdgePatternStruct p, A arg);

  }

}
