package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class EdgeSet extends EdgeExtensionBuiltin {
  public final GraphExpr graphexpr_;

  public EdgeSet(GraphExpr p1) { graphexpr_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeExtensionBuiltin.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeSet) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeSet x = (com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeSet)o;
      return this.graphexpr_.equals(x.graphexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.graphexpr_.hashCode();
  }


}
