package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class EdgeQuotation extends Edge {
  public final GraphExpr graphexpr_;

  public EdgeQuotation(GraphExpr p1) { graphexpr_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.Edge.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeQuotation) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeQuotation x = (com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeQuotation)o;
      return this.graphexpr_.equals(x.graphexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.graphexpr_.hashCode();
  }


}
