package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public abstract class Edge implements java.io.Serializable {
  public abstract <R,A> R accept(Edge.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeQuotation p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeIntegral p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeString p, A arg);

  }

}
