package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class EdgeExtenionExpr extends EdgeCollection {
  public final EdgeExtension edgeextension_;

  public EdgeExtenionExpr(EdgeExtension p1) { edgeextension_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeCollection.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeExtenionExpr) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeExtenionExpr x = (com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeExtenionExpr)o;
      return this.edgeextension_.equals(x.edgeextension_);
    }
    return false;
  }

  public int hashCode() {
    return this.edgeextension_.hashCode();
  }


}
