package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class EdgeExprStruct extends EdgeExpr {
  public final Edge edge_;
  public final VertexExpr vertexexpr_1, vertexexpr_2;

  public EdgeExprStruct(Edge p1, VertexExpr p2, VertexExpr p3) { edge_ = p1; vertexexpr_1 = p2; vertexexpr_2 = p3; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeExprStruct) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeExprStruct x = (com.biosimilarity.GraphL.model.GraphL.Absyn.EdgeExprStruct)o;
      return this.edge_.equals(x.edge_) && this.vertexexpr_1.equals(x.vertexexpr_1) && this.vertexexpr_2.equals(x.vertexexpr_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.edge_.hashCode())+this.vertexexpr_1.hashCode())+this.vertexexpr_2.hashCode();
  }


}
