package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public abstract class Formals implements java.io.Serializable {
  public abstract <R,A> R accept(Formals.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.FormalsFullForm p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.FormalsVertexForm p, A arg);

  }

}
