package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class GenEdge extends Generator {
  public final EdgeGenerator edgegenerator_;

  public GenEdge(EdgeGenerator p1) { edgegenerator_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.Generator.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.GenEdge) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.GenEdge x = (com.biosimilarity.GraphL.model.GraphL.Absyn.GenEdge)o;
      return this.edgegenerator_.equals(x.edgegenerator_);
    }
    return false;
  }

  public int hashCode() {
    return this.edgegenerator_.hashCode();
  }


}
