package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class GenVertex extends Generator {
  public final VertexGenerator vertexgenerator_;

  public GenVertex(VertexGenerator p1) { vertexgenerator_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.Generator.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.GenVertex) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.GenVertex x = (com.biosimilarity.GraphL.model.GraphL.Absyn.GenVertex)o;
      return this.vertexgenerator_.equals(x.vertexgenerator_);
    }
    return false;
  }

  public int hashCode() {
    return this.vertexgenerator_.hashCode();
  }


}
