package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class GraphConnectedPattern extends GraphDeconstructor {
  public final EdgeLabel edgelabel_;
  public final GraphDeconstructor graphdeconstructor_1, graphdeconstructor_2;

  public GraphConnectedPattern(EdgeLabel p1, GraphDeconstructor p2, GraphDeconstructor p3) { edgelabel_ = p1; graphdeconstructor_1 = p2; graphdeconstructor_2 = p3; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.GraphDeconstructor.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.GraphConnectedPattern) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.GraphConnectedPattern x = (com.biosimilarity.GraphL.model.GraphL.Absyn.GraphConnectedPattern)o;
      return this.edgelabel_.equals(x.edgelabel_) && this.graphdeconstructor_1.equals(x.graphdeconstructor_1) && this.graphdeconstructor_2.equals(x.graphdeconstructor_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.edgelabel_.hashCode())+this.graphdeconstructor_1.hashCode())+this.graphdeconstructor_2.hashCode();
  }


}
