package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class GraphBuiltinExpr extends GroundCondition {
  public final GraphBuiltin graphbuiltin_;

  public GraphBuiltinExpr(GraphBuiltin p1) { graphbuiltin_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.GroundCondition.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.GraphBuiltinExpr) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.GraphBuiltinExpr x = (com.biosimilarity.GraphL.model.GraphL.Absyn.GraphBuiltinExpr)o;
      return this.graphbuiltin_.equals(x.graphbuiltin_);
    }
    return false;
  }

  public int hashCode() {
    return this.graphbuiltin_.hashCode();
  }


}
