package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class GraphIsolatedPattern extends GraphDeconstructor {
  public final GraphDeconstructor graphdeconstructor_1, graphdeconstructor_2;

  public GraphIsolatedPattern(GraphDeconstructor p1, GraphDeconstructor p2) { graphdeconstructor_1 = p1; graphdeconstructor_2 = p2; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.GraphDeconstructor.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.GraphIsolatedPattern) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.GraphIsolatedPattern x = (com.biosimilarity.GraphL.model.GraphL.Absyn.GraphIsolatedPattern)o;
      return this.graphdeconstructor_1.equals(x.graphdeconstructor_1) && this.graphdeconstructor_2.equals(x.graphdeconstructor_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.graphdeconstructor_1.hashCode())+this.graphdeconstructor_2.hashCode();
  }


}
