package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class LocalDecl extends Decl {
  public final Binding binding_;

  public LocalDecl(Binding p1) { binding_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.Decl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.LocalDecl) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.LocalDecl x = (com.biosimilarity.GraphL.model.GraphL.Absyn.LocalDecl)o;
      return this.binding_.equals(x.binding_);
    }
    return false;
  }

  public int hashCode() {
    return this.binding_.hashCode();
  }


}
