package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public abstract class SelectionExpr implements java.io.Serializable {
  public abstract <R,A> R accept(SelectionExpr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.Selection p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.ComprehensionExpr p, A arg);

  }

}
