package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class StructuralCondition extends Condition {
  public final StructureCondition structurecondition_;

  public StructuralCondition(StructureCondition p1) { structurecondition_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.Condition.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.StructuralCondition) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.StructuralCondition x = (com.biosimilarity.GraphL.model.GraphL.Absyn.StructuralCondition)o;
      return this.structurecondition_.equals(x.structurecondition_);
    }
    return false;
  }

  public int hashCode() {
    return this.structurecondition_.hashCode();
  }


}
