package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class VertexIntensionSelection extends VertexSelectionExpr {
  public final VertexComprehension vertexcomprehension_;

  public VertexIntensionSelection(VertexComprehension p1) { vertexcomprehension_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexSelectionExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.VertexIntensionSelection) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.VertexIntensionSelection x = (com.biosimilarity.GraphL.model.GraphL.Absyn.VertexIntensionSelection)o;
      return this.vertexcomprehension_.equals(x.vertexcomprehension_);
    }
    return false;
  }

  public int hashCode() {
    return this.vertexcomprehension_.hashCode();
  }


}
