package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class VertexSum extends VertexExpr {
  public final VertexExpr vertexexpr_1, vertexexpr_2;

  public VertexSum(VertexExpr p1, VertexExpr p2) { vertexexpr_1 = p1; vertexexpr_2 = p2; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.VertexSum) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.VertexSum x = (com.biosimilarity.GraphL.model.GraphL.Absyn.VertexSum)o;
      return this.vertexexpr_1.equals(x.vertexexpr_1) && this.vertexexpr_2.equals(x.vertexexpr_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.vertexexpr_1.hashCode())+this.vertexexpr_2.hashCode();
  }


}
