package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public abstract class VertexBuiltin implements java.io.Serializable {
  public abstract <R,A> R accept(VertexBuiltin.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.SinkBuiltin p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.SourceBuiltin p, A arg);

  }

}
