package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class VertexStructureLiteral extends VertexStructureCondition {
  public final Vertex vertex_;

  public VertexStructureLiteral(Vertex p1) { vertex_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexStructureCondition.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.VertexStructureLiteral) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.VertexStructureLiteral x = (com.biosimilarity.GraphL.model.GraphL.Absyn.VertexStructureLiteral)o;
      return this.vertex_.equals(x.vertex_);
    }
    return false;
  }

  public int hashCode() {
    return this.vertex_.hashCode();
  }


}
