package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public abstract class Vertex implements java.io.Serializable {
  public abstract <R,A> R accept(Vertex.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexQuotation p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexIntegral p, A arg);
    public R visit(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexString p, A arg);

  }

}
