package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class VertexExtenionExpr extends VertexCollection {
  public final VertexExtension vertexextension_;

  public VertexExtenionExpr(VertexExtension p1) { vertexextension_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexCollection.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.VertexExtenionExpr) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.VertexExtenionExpr x = (com.biosimilarity.GraphL.model.GraphL.Absyn.VertexExtenionExpr)o;
      return this.vertexextension_.equals(x.vertexextension_);
    }
    return false;
  }

  public int hashCode() {
    return this.vertexextension_.hashCode();
  }


}
