package com.biosimilarity.GraphL.model.GraphL.Absyn; // Java Package generated by the BNF Converter.

public class VertexVariable extends VertexExpr {
  public final String lident_;

  public VertexVariable(String p1) { lident_ = p1; }

  public <R,A> R accept(com.biosimilarity.GraphL.model.GraphL.Absyn.VertexExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.GraphL.model.GraphL.Absyn.VertexVariable) {
      com.biosimilarity.GraphL.model.GraphL.Absyn.VertexVariable x = (com.biosimilarity.GraphL.model.GraphL.Absyn.VertexVariable)o;
      return this.lident_.equals(x.lident_);
    }
    return false;
  }

  public int hashCode() {
    return this.lident_.hashCode();
  }


}
